<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BFS-CA645327-N" name="com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail" tests="3" failures="0" timestamp="2020-11-26T16:46:31 AEDT" time="257.940" errors="2">
  <testcase name="addHiveBrand" time="97.221" classname="com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail">
    <error type="junit.framework.AssertionFailedError" message="Add Hive Brand Exception">
      <![CDATA[junit.framework.AssertionFailedError: Add Hive Brand Exception
at junit.framework.Assert.fail(Assert.java:47)
at com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail.addHiveBrand(UX_BeekeeperRegressionTestCasesTestRail.java:300)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- addHiveBrand -->
  <system-out/>
  <testcase name="addHiveLocationAddress" time="108.834" classname="com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail"/>
  <system-out/>
  <testcase name="UpdateAccountDetailsAndPrimaryLocation" time="51.885" classname="com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail">
    <error type="junit.framework.AssertionFailedError" message="UpdateAccountDetailsAndPrimaryLocation Exception">
      <![CDATA[junit.framework.AssertionFailedError: UpdateAccountDetailsAndPrimaryLocation Exception
at junit.framework.Assert.fail(Assert.java:47)
at com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail.UpdateAccountDetailsAndPrimaryLocation(UX_BeekeeperRegressionTestCasesTestRail.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- UpdateAccountDetailsAndPrimaryLocation -->
  <system-out/>
</testsuite> <!-- com.au.byteUX.Test.Package.UX_BeekeeperRegressionTestCasesTestRail -->
